#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building konfig.ls -> konfig.js ..."
./node_modules/.bin/lsc -cpb --no-header src/konfig.ls > dist/konfig.js
echo "(function(){" > dist/konfig.js
./node_modules/.bin/lsc -cpb --no-header src/konfig.ls >> dist/konfig.js
./node_modules/.bin/lsc tools/pack.ls >> dist/konfig.js
echo "})();" >> dist/konfig.js
./node_modules/.bin/lsc tools/pack.ls -s bootstrap > dist/konfig.widget.bootstrap.js
echo "minify konfig.js -> konfig.min.js ..."
./node_modules/.bin/uglifyjs dist/konfig.js > dist/konfig.min.js
echo "minify konfig.widget.bootstrap.js -> konfig.widget.bootstrap.min.js ..."
./node_modules/.bin/uglifyjs dist/konfig.widget.bootstrap.js > dist/konfig.widget.bootstrap.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/konfig/dev/
mkdir -p web/static/assets/lib/@plotdb/konfig/dev/
cp -R dist/* web/static/assets/lib/@plotdb/konfig/dev/

