#!/usr/bin/env bash

root=web/src/pug/block
subsets="default bootstrap"

echo "prepare..."
rm -rf dist
mkdir -p dist

echo "building index.ls -> index.js ..."
./node_modules/.bin/lsc -cpb --no-header src/index.ls > dist/index.js
echo "(function(){" > dist/index.js
./node_modules/.bin/lsc -cpb --no-header src/index.ls >> dist/index.js
./node_modules/.bin/lsc tools/pack.ls >> dist/index.js
echo "})();" >> dist/index.js
./node_modules/.bin/lsc tools/pack.ls -s bootstrap > dist/konfig.widget.bootstrap.js
echo "minify index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "minify konfig.widget.bootstrap.js -> konfig.widget.bootstrap.min.js ..."
./node_modules/.bin/uglifyjs dist/konfig.widget.bootstrap.js -m -c > dist/konfig.widget.bootstrap.min.js

for subset in $subsets; do
  for dir in $(ls $root/$subset); do
    echo "transpile widget $subset/$dir -> dist/widgets/$subset/$dir/$subset/index.html ..."
    mkdir -p dist/widgets/$subset/$dir
    ./node_modules/.bin/srcbuild-pug $root/$subset/$dir/index.pug > dist/widgets/$subset/$dir/index.html
  done
done
cp -R dist/widgets/$subset/* dist

echo "bundling blocks -> index.html ..."
./node_modules/.bin/lsc tools/bundle.ls > web/static/assets/bundle/index.html

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/konfig/dev/
mkdir -p web/static/assets/lib/@plotdb/konfig/dev/
cp -R dist/* web/static/assets/lib/@plotdb/konfig/dev/

